#!/usr/bin/env python3
"""
Simple test script for RAG+LLM system without OpenAI dependencies.
"""

import sys
import os
import logging
import time
from pathlib import Path

# Add backend directory to Python path
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from rag.retriever_service import RetrieverService

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)

def test_rag_llm_simple():
    """Test RAG system without LLM dependencies."""
    print("\n=== Testing RAG System (No LLM) ===")
    
    try:
        # Initialize RAG service
        retriever = RetrieverService()
        retriever.initialize()
        
        print("✅ RAG system initialized successfully")
        
        # Test basic search (without LLM)
        print("\n--- Testing Basic RAG Search ---")
        query = "scholarship for students"
        search_results = retriever.search(query, top_k=3)
        
        print(f"Query: '{query}'")
        print(f"Found {len(search_results)} relevant schemes:")
        
        for i, result in enumerate(search_results):
            print(f"  {i+1}. {result['scheme_name']} (Score: {result.get('similarity_score', 0):.3f})")
            print(f"     Category: {result.get('category', 'N/A')}")
            print(f"     Chunks: {len(result.get('matching_chunks', []))}")
        
        # Test with user profile
        print("\n--- Testing RAG Search with User Profile ---")
        user_profile = {
            "age": 21,
            "education": "engineering",
            "income": 250000,
            "state": "Karnataka"
        }
        
        profile_results = retriever.search(query, top_k=3, user_profile=user_profile)
        
        print(f"Query: '{query}' (with profile)")
        print(f"Found {len(profile_results)} relevant schemes:")
        
        for i, result in enumerate(profile_results):
            print(f"  {i+1}. {result['scheme_name']} (Score: {result.get('similarity_score', 0):.3f})")
            print(f"     Profile-based matching: {len(result.get('matching_chunks', []))} chunks")
        
        # Test search statistics
        stats = retriever.get_search_statistics()
        print(f"\n✅ RAG System Statistics:")
        print(f"  Total vectors: {stats['vector_store']['total_vectors']}")
        print(f"  Embedding dimension: {stats['vector_store']['embedding_dimension']}")
        print(f"  Index type: {stats['vector_store']['index_type']}")
        
        return True
        
    except Exception as e:
        print(f"✗ RAG test failed: {e}")
        return False

def test_mock_llm_response():
    """Test mock LLM response generation."""
    print("\n=== Testing Mock LLM Response ===")
    
    # Mock structured response that would be generated by LLM
    mock_response = {
        "schemes": [
            {
                "name": "National Scholarship Portal",
                "why_eligible": "Based on your engineering background and age of 21, you meet the eligibility criteria for technical scholarships. Your academic performance and field of study make you a strong candidate for merit-based scholarships.",
                "benefits": "Financial assistance covering tuition fees, hostel expenses, and study materials. Technical students often get additional benefits for equipment and project work.",
                "how_to_apply": "1. Register on scholarships.gov.in with your academic details\n2. Complete your profile with engineering branch information\n3. Upload mark sheets and recommendation letters\n4. Apply for technical scholarships specifically\n5. Submit applications before deadlines",
                "documents": ["Aadhaar card", "Engineering college ID", "Mark sheets", "Income certificate", "Bank account details"],
                "confidence_score": 0.92
            },
            {
                "name": "Pradhan Mantri Awas Yojana",
                "why_eligible": "As a 21-year-old with income of ₹2,50,000, you fall under the Economically Weaker Section (EWS) category for PMAY benefits. Your age and income level make you eligible for the interest subsidy.",
                "benefits": "Interest subsidy of 6.50% on home loans up to 20 years. This can save you approximately ₹2,67,000 on a ₹50,00,000 loan over 20 years.",
                "how_to_apply": "1. Apply through your bank or housing finance company\n2. Submit income and identity proof\n3. Provide property details\n4. Wait for subsidy approval and credit",
                "documents": ["Aadhaar card", "PAN card", "Income certificate", "Bank statements", "Property documents"],
                "confidence_score": 0.88
            }
        ]
    }
    
    print("✅ Mock LLM response generated:")
    print(f"  Total schemes: {len(mock_response['schemes'])}")
    
    for i, scheme in enumerate(mock_response['schemes']):
        print(f"  {i+1}. {scheme['name']}")
        print(f"     Confidence: {scheme['confidence_score']}")
        print(f"     Why Eligible: {scheme['why_eligible'][:50]}...")
    
    return True

def main():
    """Run RAG+LLM tests."""
    print("Starting RAG+LLM system tests...")
    
    # Change to backend directory
    backend_dir = Path(__file__).parent
    os.chdir(backend_dir)
    
    # Run tests
    tests_passed = 0
    total_tests = 2
    
    # Test RAG system
    if test_rag_llm_simple():
        tests_passed += 1
    
    # Test mock LLM response
    if test_mock_llm_response():
        tests_passed += 1
    
    print(f"\n=== Test Results ===")
    print(f"Passed: {tests_passed}/{total_tests}")
    
    if tests_passed == total_tests:
        print("✅ All RAG+LLM tests passed!")
        print("\n🎯 System ready for integration with OpenAI API!")
        return 0
    else:
        print("✗ Some tests failed!")
        return 1

if __name__ == "__main__":
    exit(main())
